namespace MeditationApp.Models;

public enum MeditationSessionStatus
{
    REQUESTED,  // Session is being generated by the backend
    FAILED,     // Something went wrong during creation
    COMPLETED    // Session is ready for playback
}

public static class MeditationSessionStatusExtensions
{
    public static string ToDisplayString(this MeditationSessionStatus status)
    {
        return status switch
        {
            MeditationSessionStatus.REQUESTED => "Generating...",
            MeditationSessionStatus.FAILED => "Failed to generate",
            MeditationSessionStatus.COMPLETED => "Ready to play",
            _ => "Unknown"
        };
    }

    public static Color ToStatusColor(this MeditationSessionStatus status)
    {
        return status switch
        {
            MeditationSessionStatus.REQUESTED => Colors.Orange,
            MeditationSessionStatus.FAILED => Colors.Red,
            MeditationSessionStatus.COMPLETED => Colors.Green,
            _ => Colors.Gray
        };
    }
} 